### ISSUE TITLE
Current master has empty Import, Server Query and Quest Givers option pages

### ISSUE THREAD

**Issue by NostraDavid** [NethanosGit/EveryQuest#1]
Just found this via reddit and tried the newest version, but the Import, Server Query and Quest Givers option screens were empty. Using an older version (`9ca0374ff623990c3dff0a94333338df8abfc5a9`) worked fine.

**Comment by NethanosGit** [comment]
I am only working on the Quest Givers, not going into the import and server query part. But for me it works ok. I just downloaded the addons again, and they worked fine for me. Could you share a screenshot with the addons activated and one with how you see the quest givers tab?

**Comment by vrusso-kong** [comment]
I too am having the same issue and i just downloaded the files about 20 minutes ago. I'll attach screen shots of what i see.


<img width="882" alt="Screen Shot 2022-05-07 at 11 33 40 PM" src="https://user-images.githubusercontent.com/20424759/167280639-dcd3b068-a25f-4cee-b2f8-6753550f8410.png">
<img width="921" alt="Screen Shot 2022-05-07 at 11 33 35 PM" src="https://user-images.githubusercontent.com/20424759/167280642-f1840d4d-66d0-470d-a460-293cfd9a82b9.png">
<img width="897" alt="Screen Shot 2022-05-07 at 11 33 29 PM" src="https://user-images.githubusercontent.com/20424759/167280644-2d48a52d-1e41-4e99-a3e9-a2954b68319e.png">
<img width="883" alt="Screen Shot 2022-05-07 at 11 33 24 PM" src="https://user-images.githubusercontent.com/20424759/167280646-e2a35b62-3667-4192-8005-9383ce590d2f.png">

**Comment by NethanosGit** [comment]
Fixed
